import React from 'react';
import {AbsoluteFill, staticFile} from 'remotion';
import {Audio} from '@remotion/media';
import {FilmCanvas} from './gl/FilmCanvas';
import {createEarthWorld, makeEarthWorld} from './world/EarthWorld';
import {COLORS} from './brand';
import {Overlay} from './overlay/Overlay';

// The film: one continuous WebGL world + brand DOM layers on top.
// Soundtrack: generated by tools/make_soundtrack.py (48 kHz / 24-bit, -14 LUFS).
export const Film: React.FC<{hide?: string[]; muted?: boolean}> = ({hide, muted}) => {
  const factory = React.useMemo(() => (hide && hide.length ? makeEarthWorld({hide}) : createEarthWorld), [hide]);
  return (
    <AbsoluteFill style={{backgroundColor: COLORS.black}}>
      <FilmCanvas factory={factory} />
      <Overlay />
      {!muted && <Audio src={staticFile('audio/soundtrack.wav')} />}
    </AbsoluteFill>
  );
};
